" My .vimrc -- abheyogy (abheyogy@icloud.com)
" github.com/abheyogy
" Note: Use vim or die!

" Vundle
  " Pre-Configuration
    set nocompatible		" Switch off VI backwards compatability
    filetype off		" Using Vundle to manage dependencies

  " Vundle auto-install logic.
    let install_vundle=1
    let vundle_readme=expand("$HOME/.vim/bundle/Vundle.vim/README.md")

  " Check if Vundle is installed.
    if !filereadable(vundle_readme)
      echo "Installing Vundle ..."
      echo ""
      silent !git clone https://github.com/VundleVim/Vundle.vim $HOME/.vim/bundle/Vundle.vim
      let install_vundle=0
    endif

    set rtp+=$HOME/.vim/bundle/Vundle.vim

  " Install Vim Plugins
    call vundle#begin()		" Start Vundle Plugin Configuration

    Plugin 'VundleVim/Vundle.vim'
    Plugin 'christoomey/vim-tmux-navigator'
    Plugin 'vim-syntastic/syntastic'

    " SaltStack Plugins
    Plugin 'saltstack/salt-vim'
    Plugin 'stephpy/vim-yaml'
    Plugin 'jinja'

    " Code Niceness
    Plugin 'StripWhiteSpaces'
    Plugin 'closetag.vim'
    Plugin 'autofold.vim'

    " SCM Related
    Plugin 'jisaacks/GitGutter'
    Plugin 'vim-gitgutter.git'
    Plugin 'tpope/vim-fugitive'

    " Install first time Vundle plugins.
    if install_vundle == 0
      echo "Installing Vundle & Plugins, hold tight!"
      echo ""
      :PluginInstall
    endif

  call vundle#end()

  " Post Configuration
    filetype on
    filetype plugin indent on

  " End Vundle Section Logic.

" General Configuration

  " Color Scheme!
    syntax enable
      try
        colorscheme solarized
        set background=dark
      catch
        colorscheme default
      endtry

  " Autoreload .vimrc
    autocmd! bufwritepost .vimrc source %

  " Detect encoding
    set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1

  " Misc
    set timeoutlen=50
    set laststatus=2
    set showtabline=2
    set showmatch
    set backspace=indent,eol,start
    set noshowmode
    set showcmd
    set wildmenu
    set lazyredraw
    set encoding=utf-8
    set fillchars+=stl:\ ,stlnc:\
    set spell
    set cursorline
    set foldlevelstart=6
    set foldlevel=5

  " Undo my life
    set history=1000
    set undolevels=700

  " Disable backup and swap files
    set nobackup
    set nowritebackup
    set noswapfile

  " Formatting
    set nowrap			" Do not wrap long lines
    set autoindent		" Indent at the same level as previous line
    set expandtab		" Tabs are spaces not tabs
    set tabstop=4		" Indent every four columns
    set softtabstop=4		" Backspace deletes tabs
    set shiftwidth=4		" Shift by 4 spaces ">>/<<"
    set splitright		" Vsplit to right
    set splitbelow		" Split to below
    set pastetoggle=<F5>        " Toggle paste mode

  " Searching
    set incsearch
    set hlsearch
    set ignorecase
    set smartcase
    set gdefault
    set incsearch
    set showmatch

  " Buffers & Splits ...
    set diffopt+=vertical

  " Disable arrow keys!
    nnoremap <up> <nop>
    nnoremap <down> <nop>
    nnoremap <left> <nop>
    nnoremap <right> <nop>
    nnoremap <up> <nop>
    nnoremap <down> <nop>
    nnoremap <left> <nop>
    nnoremap <right> <nop>
    nnoremap j gj
    nnoremap k gk

  " Settings for ctrlp
    let g:ctrlp_max_height = 30
    set wildignore+=*.pyc
    set wildignore+=*_build/*
    set wildignore+=*/coverage/*

  " Enable & Disable Mouse
    set mouse=a          " Automatically Enable mouse usage
    set mousehide        " Hide the mouse cursor while typing
