# Performance timing
zmodload zsh/zprof

# History configuration
HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history

# Load configurations
source ${HOME}/.opts.zsh
source ${HOME}/.plugins.zsh
source ${HOME}/.aliases.zsh
source ${HOME}/.env.zsh

# Disable autocorrect
setopt nocorrectall

# Performance profiling: uncomment to benchmark
zprof

# add Pulumi to the PATH
export PATH=$PATH:/home/pundalika/.pulumi/bin
